In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

In [2]:
df1 = pd.read_csv("Sales_add.csv")
df1.head(5)

Month      Region      Manager  Sales_before_digital_add(in $)  \
0  Month-1  Region - A  Manager - A                          132921   
1  Month-2  Region - A  Manager - C                          149559   
2  Month-3  Region - B  Manager - A                          146278   
3  Month-4  Region - B  Manager - B                          152167   
4  Month-5  Region - C  Manager - B                          159525   

   Sales_After_digital_add(in $)  
0                         270390  
1                         223334  
2                         244243  
3                         231808  
4                         258402

In [3]:
df1.isna().sum()

Month                             0
Region                            0
Manager                           0
Sales_before_digital_add(in $)    0
Sales_After_digital_add(in $)     0
dtype: int64

In [4]:
df1.describe()

Sales_before_digital_add(in $)  Sales_After_digital_add(in $)
count                       22.000000                      22.000000
mean                    149239.954545                  231123.727273
std                      14844.042921                   25556.777061
min                     130263.000000                  187305.000000
25%                     138087.750000                  214960.750000
50%                     147444.000000                  229986.500000
75%                     157627.500000                  250909.000000
max                     178939.000000                  276279.000000

# 1.changes after stepping into digital marketing.

H0 : No Increase in sales post digital marketing

H1 : Increase in sales post digital marketing

In [5]:
stats.ttest_rel(df1['Sales_After_digital_add(in $)'],df1['Sales_before_digital_add(in $)'],alternative='greater')

Ttest_relResult(statistic=12.09070525287017, pvalue=3.168333502287889e-11)

alpha = 0.05

p<0.05 We reject null hypothesis,

There is increase in sales post digital marketing.

# 2.The company needs to check whether there is any dependency between the features “Region” and “Manager”.

In [7]:
##here we have to do chi square test for independance since we have to see weather region and manager are related or not

##H0: The two variables region and manager are independent.

##H1: The two variables region and manager are not independent.

dfchi=pd.crosstab(df1['Region'],df1['Manager'])
print(dfchi)

Manager     Manager - A  Manager - B  Manager - C
Region                                           
Region - A            4            3            3
Region - B            4            1            2
Region - C            1            3            1


In [8]:
dfchi.values 
Observed_Values = dfchi.values 
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[4 3 3]
 [4 1 2]
 [1 3 1]]


In [9]:
result=stats.chi2_contingency(dfchi)
result

(3.050566893424036,
 0.5493991051158094,
 4,
 array([[4.09090909, 3.18181818, 2.72727273],
        [2.86363636, 2.22727273, 1.90909091],
        [2.04545455, 1.59090909, 1.36363636]]))

In [10]:
Expected_Values=result[3]
Expected_Values

array([[4.09090909, 3.18181818, 2.72727273],
       [2.86363636, 2.22727273, 1.90909091],
       [2.04545455, 1.59090909, 1.36363636]])

In [20]:
no_of_rows=len(dfchi.iloc[0:3,0])
no_of_columns=len(dfchi.iloc[0,0:3])
Degreeff=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",Degreeff)
alpha = 0.05


Degree of Freedom:- 4


In [15]:
from scipy.stats import chi2
chi_square=sum([(0-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]+chi_square[2]
print("chi-square statistic:",chi_square_statistic)

chi-square statistic: 22.0


In [21]:
critical_value= chi2.ppf(q=1-alpha,df=Degreeff)
print('critical_value:',critical_value)

critical_value: 9.487729036781154


In [22]:
p_value=1-chi2.cdf(x=chi_square_statistic,df=Degree_of_Freedom)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',Degreeff)



p-value: 0.000200420409482982
Significance level:  0.05
Degree of Freedom:  4


In [23]:
if chi_square_statistic>=critical_value:
    print("Reject H0: The two variables region and manager are independent")
else:
    print("Retain H0: The two variables region and manager are independent")
    
if p_value<=alpha:
    print("Reject H0: The two variables region and manager are independent")
else:
    print("Retain H0: The two variables region and manager are independent")

Reject H0: The two variables region and manager are independent
Reject H0: The two variables region and manager are independent


since we reject h0 ,there is any dependency between the features “Region” and “Manager.